name: Publish package to npmjs
on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: 22
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn clean-package -- scripts devDependencies packageManager
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
